- name: variables from file
  host: localhost
  vars_files: 
  - variables.yaml
  tasks: 
  - name: printing variables
    ansible.builtin.debug: 
     msg: "we r learning {{NAME}}, duration is: {{DURATION}}" 